version: 1.0
configuration:
  backupPath: C:\repos\Backup
  adDomain: mydomain.local
  shellConfiguration:
    pathToOneNote: C:\Program Files\Microsoft Office\root\Office16\ONENOTE        
    autostart: true
  showDiagnosticInformation: false
  defaultCommand: find  
  codeEditor: C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\Code.exe
  commandDesignOverrides:
  - name: find    
    suggestions: "Eskilstuna \u00F6rebro|lunch"    
  - name: start    
    suggestions: "ac|cheat|steam|wheel"
  repository: https://github.com/PowerCommands/PowerCommands2022
  displayTagsMaxLength: 50
  displayUrlMaxLength: 30
  openAiApiUrl: https://api.openai.com/v1/engines/gpt-3.5-turbo/completions
  openAiMaxTokens: 50
  metadata:
    name: Test
    description: En exempelbeskrivning
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 173831af7e77b8bd33e32fce0b4e646d
    name: Serialog
  components:  
  - component: PainKiller.PowerCommands.KnowledgeDBCommands.dll
    checksum: c8d128cde99a5ee06b56e8337c10b1e2
    name: KDB commands
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 30cc55b7c6f29f951be3df97f634fb71
    name: PainKiller Core
  bookmark:
    bookmarks:    
    - name: Images
      path: C:\Users\%USERNAME%\OneDrive
      index: 0
  proxyCommands:
    - name: wc
      workingDirctory: D:\Program\PainKiller\PainKiller.WindowsCommands
      commands: 
      - start
  secret:
    secrets:
    - name: kdb_gpt
      options:
        target: User
  environment:
    variables:
    - name: KEY_VAULT_NAME
      environmentVariableTarget: User
    - name: AZURE_CLIENT_ID
      environmentVariableTarget: User 