version: 1.0
configuration:
  backupPath: C:\repos\Backup
  shellConfiguration:
    pathToOneNote: C:\Program Files\Microsoft Office\root\Office16\ONENOTE    
    displaySeparator: \t
    autostart: true
  showDiagnosticInformation: false
  defaultCommand: find  
  codeEditor: C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\Code.exe
  repository: https://github.com/PowerCommands/PowerCommands2022
  displayTagsMaxLength: 50
  displayUrlMaxLength: 30
  metadata:
    name: Test
    description: En exempelbeskrivning
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 173831af7e77b8bd33e32fce0b4e646d
    name: Serialog
  components:  
  - component: PainKiller.PowerCommands.KnowledgeDBCommands.dll
    checksum: c8d128cde99a5ee06b56e8337c10b1e2
    name: KDB commands
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 30cc55b7c6f29f951be3df97f634fb71
    name: PainKiller Core
  bookmark:
    bookmarks:
    - name: Program
      path: C:\Program Files
      index: 0
  secret:
    secrets:
    - name: localDB
      options:
        target: User
  environment:
    variables:
    - name: KEY_VAULT_NAME
      environmentVariableTarget: User
    - name: AZURE_CLIENT_ID
      environmentVariableTarget: User 